<?php
/**
 * @file
 * Install, uninstall, and update implementations for entity modified module.
 */

/**
 * Implements hook_schema().
 */
function entity_modified_schema() {
  $schema['entity_modified'] = array(
    'description' => 'Entity modification timestamps for entities that do not support it natively.',
    'fields' => array(
      'entity_type' => array(
        'type' => 'varchar',
        'length' => 128,
        'not null' => TRUE,
        'default' => '',
        'description' => 'The entity type this modified tracker refers to.',
      ),
      'entity_id' => array(
        'type' => 'int',
        'size' => 'big',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The entity ID this modified tracker refers to.',
      ),
      'modified' => array(
        'description' => 'The Unix timestamp when the entity was most recently saved.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('entity_type', 'entity_id'),
  );

  return $schema;
}

/**
 * Enlarge entity_type and entity_id columns for upgrades from Drupal 7.
 */
function entity_modified_update_1000() {
  $entity_type_column = array(
    'type' => 'varchar',
    'length' => 128,
    'not null' => TRUE,
    'default' => '',
    'description' => 'The entity type this modified tracker refers to.',
  );
  db_change_field('entity_modified', 'entity_type', 'entity_type', $entity_type_column);

  $entity_id_column = array(
    'type' => 'int',
    'size' => 'big',
    'unsigned' => TRUE,
    'not null' => TRUE,
    'default' => 0,
    'description' => 'The entity ID this modified tracker refers to.',
  );
  db_change_field('entity_modified', 'entity_id', 'entity_id', $entity_id_column);
}
